[package]
name = "grapple-probe-proto"
version = "0.1.0"
authors = [
    "Jonathan Herbst <jonathan.herbst@grapple.systems>",
    "Seth Pierson <seth.pierson@grapple.systems>",
]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
num_enum = { version = "0.7.5", default-features = false }
packet-gen = { path = "../../packet-gen" }
