[package]
name = "device-info"
version = "0.1.0"
authors = [
    "Jonathan Herbst <jonathan.herbst@grapple.systems>",
    "Seth Pierson <seth.pierson@grapple.systems>",
]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
fletcher = "1.0"

[[bin]]
name = "deviceinfo"
path = "src/bin/device_info.rs"
