name: grapple-probe-firmware

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust ${{ matrix.toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: thumbv6m-none-eabi
        override: true

    - name: Build
      working-directory: ./grapple-probe-firmware
      run: cargo build --release --verbose

    - name: Run cmsis-dap tests
      working-directory: ./cmsis-dap
      run: cargo test --verbose