name: Grapple Probe CLI (Build and Test)

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    
    - name: Install Arm GCC (ubuntu)
      if: contains(inputs.runner, 'ubuntu') && inputs.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu

    - name: Build
      working-directory: ./grapple-probe-cli
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      run: |
        rustup target add ${{ inputs.target }}
        cargo build --release --verbose --target ${{ inputs.target }}

    - name: Upload Artifacts (windows)
      if: ${{ contains(inputs.target, 'windows') }}
      uses: actions/upload-artifact@v7
      with:
        name: grapple-probe-cli-${{ inputs.target }}
        path: ./grapple-probe-cli/target/${{ inputs.target }}/release/grapple-probe-cli.exe

    - name: Upload Artifacts (mac/linux)
      if: ${{ !contains(inputs.target, 'windows') }}
      uses: actions/upload-artifact@v7
      with:
        name: grapple-probe-cli-${{ inputs.target }}
        path: ./grapple-probe-cli/target/${{ inputs.target }}/release/grapple-probe-cli