name: grapple-probe-firmware-ci

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install Rust
      run: rustup target add thumbv6m-none-eabi

    - name: Build
      working-directory: ./grapple-probe-firmware
      run: cargo build --release --verbose

  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run cmsis-dap tests
      working-directory: ./cmsis-dap
      run: cargo test --verbose

    - name: Run device-info tests
      working-directory: ./device-info
      run: cargo test --verbose